### PR TITLE
Tm gradient fix

### PR DESCRIPTION
**Pull request by FoleyLab**
## Description
Fixes the _compute_tm_gradient method and its unit test
I tried to explain what was fixed in this zoom video: https://wpunj.zoom.us/rec/share/Y7DlavKHxzNYd9Rie7QHe4WBtsUkaPANiLmJEp0FiRUNtRwJd6eCULXnJNjdtIdN.uCeK4IiGvOgwAHGW Passcode: s^fyK78v 

## Todos

  - [ ]  Watch the brief explanation in zoom and take a look at the revised code and let me know if you have any questions!
  - [ ]  Next step will be to complete the compute_spectrum_gradient method, and we can meet whenever you are all ready to discuss!

### CODE REVIEW

**Comment by Suchanekf** [comment]
Thank you so much for the video and the great explanation. Both the code and the test look excellent.

**Review by Suchanekf — APPROVED** [review]
Thank you so much for the video and the great explanation. Both the code and the test look excellent.

**Comment by FoleyLab** [comment]
Thank you for reviewing @Suchanekf!  
I updated this pull request with a start to the compute_spectrum_gradient() method and put in the code to compute the reflectivity gradient and also recorded a video with some additional details to help orient you towards finishing the code for the transmissivity gradient. Here is the link to the video and we can all also meet to discuss if needed.
https://wpunj.zoom.us/rec/share/jwBHgtc5JCmoXqc8o6i6d9Vf6a5jQkzs-KJFsnvSX0T1zWJvDQvrlijsthekeUIR.SFQmvP3pm3y8yAP4 Passcode: 8RIf2#17

**Comment by FoleyLab** [comment]
More discussion about the gradients with @Suchanekf and @lakatosa1 here: https://wpunj.zoom.us/rec/share/xtw-TilZLyGw1s7_YEoIiDFUDmWl773OM3bqzbB547dKr7eETkvCmAii4qEMDFLh.kkvEXfOJPWRSXb2T Passcode: vec?v9?G

**Comment by FoleyLab** [comment]
merging this since our last merge broke the CI and this PR fixes them :)

**Pull request merged**
