### PR TITLE
Cooling

### PR DESCRIPTION
**Pull request by FoleyLab**
## Description
Added functionality for radiative cooling applications

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Radiative power calculated for cooling passes tests
  - [x] Solar absorbed power (heating) passes tests
  - [ ] Atmospheric radiation power (heating) implemented, does not pass

## Questions
- [ ] What is wrong with atmospheric radiation power?

### CODE REVIEW

**Comment by FoleyLab** [comment]
@Suchanekf @Belloj3 @lakatosa1 The atmospheric radiation is passing now too, this morning I found a missing factor of cos(theta) that I think should be there... should double check the Fan paper about this

**Comment by Suchanekf** [comment]
Looks great! We may still need to add the cooling power of the structure by using equation 33 that is Pcool= Prad(T)-Patm(Tamb)-Psun. Since we already calculated P_sun, P_atm, P_rad.

**Review by Suchanekf — APPROVED** [review]
Looks great! We may still need to add the cooling power of the structure by using equation 33 that, is Pcool= Prad(T)-Patm(Tamb)-Psun. Since we already calculated P_sun, P_atm, P_rad.

**Comment by FoleyLab** [comment]
> Looks great! We may still need to add the cooling power of the structure by using equation 33 that, is Pcool= Prad(T)-Patm(Tamb)-Psun. Since we already calculated P_sun, P_atm, P_rad.

Yes indeed!  
We should also create a single method (perhaps `def compute_radiative_cooling():` within em.py that contains all of the code that is currently between lines 91 and 107 of em.py, after self._parse_therml_input(args) on line 88, we would simply call `self.compute_radiative_cooling()` rather than have all of those lines.

Would you all (@Suchanekf @Belloj3 @lakatosa1 and Samar) like to give that a try?

**Pull request merged**
